### ISSUE TITLE
IndexError in the client

### ISSUE THREAD

**Issue by AadityaNair** [ffledgling/dtella#12]
After the latest update, Dtella gives this error:

``` python
C - Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 214, in doRead
    return self._dataReceived(data)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 220, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/lib64/python2.7/site-packages/twisted/protocols/basic.py", line 454, in dataReceived
    self.lineReceived(line)
--- <exception caught here> ---
  File "/home/Prometheus/dtella/dtella/client/dc.py", line 98, in lineReceived
    fn(*args)
  File "/home/Prometheus/dtella/dtella/client/dc.py", line 162, in d_Key
    self.sendLine("$Key %s" % lock2key(self.lock))
  File "/home/Prometheus/dtella/dtella/common/util.py", line 96, in lock2key
    key[0] = lock[0] ^ lock[-1] ^ lock[-2] ^ 5
exceptions.IndexError: array index out of range
```

**Comment by AadityaNair** [comment]
OS is Fedora 21 using Valknut 0.4.9

**Comment by nehaljwani** [comment]
@AadityaNair  I am not able to reproduce this error.
![screenshot from 2015-03-15 23 29 14](https://cloud.githubusercontent.com/assets/1779189/6657235/5b2107a0-cb6b-11e4-9262-3dffbe1995a0.png)
