### ISSUE TITLE
Unhandled urllib2.HTTPErrors

### ISSUE THREAD

**Issue by pmarks-net** [ffledgling/dtella#16]
The following stack traces were sent to bugs@dtella.org.  They appear to be related to your fork:

```
[10:21] <*Dtella> Something bad happened.  You might want to email this to bugs@dtella.org so we'll know about it:
Version: Dtella-Hub 2015.03.08.14.52/W
Traceback (most recent call last):
  File "twisted\internet\selectreactor.pyo", line 149, in _doReadOrWrite
  File "twisted\internet\tcp.pyo", line 215, in doRead
  File "twisted\internet\tcp.pyo", line 221, in _dataReceived
  File "twisted\protocols\basic.pyo", line 454, in dataReceived
--- <exception caught here> ---
  File "dtella\client\dc.pyo", line 98, in lineReceived
  File "dtella\client\dc.pyo", line 719, in d_PublicMsg
  File "dtella\client\dc.pyo", line 1074, in commandInput
  File "dtella\client\dc.pyo", line 1310, in handleCmd_READ
  File "urllib2.pyo", line 154, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default
urllib2.HTTPError: HTTP Error 403: Forbidden
```
## 

```
[00:16] <*Dtella> Something bad happened.  You might want to email this to bugs@dtella.org so we'll know about it:
Version: Dtella-Hub 2015.03.15.15.08/L
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 215, in doRead
    return self._dataReceived(data)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 221, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 454, in dataReceived
    self.lineReceived(line)
--- <exception caught here> ---
  File "/home/bringer/dtella/src/dtella/client/dc.py", line 98, in lineReceived
    fn(*args)
  File "/home/bringer/dtella/src/dtella/client/dc.py", line 719, in d_PublicMsg
    if self.bot.commandInput(out, text[1:], '!'):
  File "/home/bringer/dtella/src/dtella/client/dc.py", line 1074, in commandInput
    f(wrapped_out, cmd[1:], prefix)
  File "/home/bringer/dtella/src/dtella/client/dc.py", line 1310, in handleCmd_READ
    response = urllib2.urlopen(local.read_board_view_url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 504: Gateway Time-out
```
## 

Also, it might be a good idea to replace that email address with one you control, or a link to your GitHub issues page.

**Comment by spMohanty** [comment]
whoever is trying to work on this issue, can refer to my comments on https://github.com/ffledgling/dtella/commit/57f5514a973a3c7b2ed444d07b3fc3e95612b70a#diff-294f88bdf22b65e7d12deb35ed329d35R175  for the why and hows to fix this.

**Comment by nehaljwani** [comment]
Well, the read-board was hosted on markdownshare.com. And the owner, Steve Kemp, said to me:  "The application is designed to host text and markdown.  It is not designed to host other content - and that is the reason it was blocked." So, we need to find another source for hosting read board now.

**Comment by nehaljwani** [comment]
On another note, should we edit 'bugs@dtella.org' to some other email? What say, @ffledgling ?

**Comment by AadityaNair** [comment]
We can link it to [issues](https://github.com/ffledgling/dtella/issues) here.

**Comment by AadityaNair** [comment]
Also, markdownshare.com has their whole source [here](https://github.com/skx/markdownshare.com).
Can we host it here ?
